# Generated by Django 2.0 on 2020-12-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='url',
            field=models.TextField(default='decide-SAiY97mD5LH43FnzH3vbRQ'),
            preserve_default=False,
        ),
    ]
